# Choose name of model. Current supported: jeff, tadashi
model: "layout"

# Session code used as prefix of saved file
session_code: "segment/CENet_3"

# Paths to pretrained weights (.pth or .pt), if left blank, train from scratch
# pretrained_path: "checkpoints/JeffLayout-Kawasakikisen-Finetune-1536/JeffLayout-Kawasakikisen-Finetune-1536_epoch00010_F1-score0.895635217_Precision0.877025002_Recall0.921593639.pth"
pretrained_path: /mnt/sda1/code/github/ngtrkn/workspace/checkpoints/segment/CENet_2/segment/CENet_2_epoch00050.pth

# Number of training epochs
n_epochs: 100

# Batch size
batch_size: 4

# Number of workers in data loader
num_workers: 4

# Learning rate
learning_rate: 0.001

# Validate every n epochs
n_epochs_validation: 1

# metric to determine best checkpoint. Currently support: "F1-score", "Precision", "Recall"
best_metrics:
  - F1-score

# Checkpoint will be saved if one of any best_metric improve.
# If you want to save all ckpts, set to False
save_best_only: False

# "all": a checkpoint is consider better than last checpoint is all of its best_metrics result improved
# "any": ___________________________________________________ is one of ________________________________
metrics_compare_mode: all

# If you want to automatically detect checkpoint and resume training ,set to True.
# If you want to train from scratch with chosen pretrained_weight, set to False
resume_training: True

# Paths to train dataset
train_dataset:
  - /mnt/sda1/data/cinnamon/layout/Invoice_Train/AruNET_Invoice_Training
  - /mnt/sda1/data/cinnamon/layout/Medica_Train/Medica_All_prepared
  - /mnt/sda1/data/cinnamon/layout/NTTD2_75
  - /mnt/sda1/data/cinnamon/layout/NTTD2_98
  - /mnt/sda1/data/cinnamon/layout/NTTD4
  - /mnt/sda1/data/cinnamon/layout/SCSK_Train/SCSK_Train
  - /mnt/sda1/data/cinnamon/layout/Yusen_20200311_0319_trainning_data/20200311_0319_trainning_data
  - /mnt/sda1/data/cinnamon/layout/Yusen_20200323_0410_trainning_data_layout/Yusen_20200323_0410_trainning_data_layout
  - /mnt/sda1/data/cinnamon/paragraph/masks

# Paths to valid dataset
valid_dataset:
  # - "Data/PoC_Kawasakikisen_SOF_validation.zip"

# Use on-the-fly augmentation while training
use_augmentation: False

# Only run validation on valid dataset without trainingp
valid_only: False

# Do not show progress bar, good for SageMaker session
disable_progress_bar: False

# Path to checkpoint saving directory
save_dir: "checkpoints/"

# Extensions for saving and exporting
model_save_extension: ".pth"
model_export_extension: ".pt"

# GPU devices ids: "-1" for cpu, or > 0 for choose gpu device, default using gpu-0
gpu_ids: "0"

num_classes: 4
